### ISSUE TITLE
How to resolve the problem of 'Trying to abandon more columns than allowed'?

### ISSUE THREAD

**Issue by AppleStar2** [quantumgizmos/bp_osd#7]
Hi.
I am interested in your research and I try to use a new parity check matrix(248*1116) as input. However, the code seems like throwing an error 'Trying to abandon more columns than allowed'. What should I do to acquire the simulated result？

**Comment by AppleStar2** [comment]
The input is CSS code with the hz logical check method

**Comment by quantumgizmos** [comment]
Hi. In the first instance you should try reducing the OSD order to zero (it is set to 40 in the default example). If you can send the parity check matrix matrix you are working on I can try and diagnose the problem more precisely.

**Comment by AppleStar2** [comment]
Thanks for your enthusiastic help.
The parity check martrixs is attached on the letter. If it is convenient, can you apply a Partity-to-alist code?The parity-to-alist code that I used is attached on the letter too,but the simulated result is amazing——1000 codes are all decoded wrong.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quantumgizmos/bp_osd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quantumgizmos/bp_osd] How to resolve the problem of 'Trying to abandon more columns than allowed'? (#7)





 
Hi. In the first instance you should try reducing the OSD order to zero (it is set to 40 in the default example). If you can send the parity check matrix matrix you are working on I can try and diagnose the problem more precisely.

**Comment by quantumgizmos** [comment]
Hi. I can't see the parity check matrix? Perhaps it didn't attach properly. Could you send it to me? 
joschka@roffe.eu
