### ISSUE TITLE
Obtain the iteration count from the decoder

### ISSUE THREAD

**Issue by sbates130272** [quantumgizmos/bp_osd#9]
In LDPC analysis it is usually desirable to obtain the iterations required to converge the decoder. Currently this information is not passed out of the decoder. It would be useful to add this.

**Comment by quantumgizmos** [comment]
I've added a new branch ('issue9') with an updated example script that logs the min/max iteration depths as well as the average. Runs in which BP fails (and OSD is called) are ignored in these statistics.

**Comment by sbates130272** [comment]
I will test the new branch later this week thanks!

**Comment by sbates130272** [comment]
@quantumgizmos sorry for the delay. This looks good though I see two issues:

1. We don't need all those decimal places for iterations ;-). 2 decimal places should suffice. 
2. The output JSON is sorted alphabetically so that average result is seperate from the min and max. Maybe rename them so they are on consecutive lines?

**Comment by sbates130272** [comment]
Oh one more thing @quantumgizmos. Can we update the command line output to include the min/avg/max iterations too? Useful to know when running a longer sim.

**Comment by quantumgizmos** [comment]
@sbates130272 I get the following error when trying to compile the issue9-sb branch:

` error: request for member ‘elapsed_time_seconds’ in ‘time’, which is of non-class type ‘time_t(time_t*) throw ()’ {aka ‘long int(long int*)’}
  279 |             output["runtime_seconds"] = time.elapsed_time_seconds();`
